{% set version = "0.14.0" %}

package:
  name: dipy
  version: {{ version }}

source:
  fn: dipy-{{ version }}.tar.gz
  url:
    https://files.pythonhosted.org/packages/55/c6/447e170205d056413118bb8db2ae35b9ea294ecb152f7afe120ab99fd5b1/dipy-{{ version }}.tar.gz
  md5: 2a0f81ccaed6fad7c0776462ea18ad29

build:
    number: 1
    script:
      - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64   # [win64 and py3k]
      - python setup.py install
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
  build:
    - python
    - numpy
    - nibabel
    - cython
    - gcc  # [not win]
  run:
    - python
    - numpy
    - scipy
    - nibabel
    - scikit-learn
    - matplotlib
    - cvxopt  # [not win]
    - pytables
    - libgcc  # [not win]
    - vtk  # [py27]
test:
  imports:
    - dipy

about:
  home: https://nipy.org/dipy
  license:  3-clause BSD
  license_file: LICENSE
  summary: Diffusion MR Imaging in Python

extra:
  recipe-maintainers:
    - arokem
    - garyfallidis
    - skoudoro
