{% set version = "1.3.0" %}
{% set name = "dipy" %}

package:
  name: dipy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: c5be00719a01f63be0e22eed389eaa0ec2423a863e16a83dea3e9eeaa9cf6034

build:
  number: 1
  script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64   # [win64 and vc==14]
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - {{ compiler('c') }}
  host:
    - python
    - numpy
    - nibabel
    - cython
    - pip
    - tqdm
    - h5py
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - nibabel
    - scikit-learn
    - matplotlib-base
    - cvxpy
    - pytables
    - vtk
    - tqdm
    - h5py
    - pandas
    - pytables
    - scikit-image
    - statsmodels

test:
  imports:
    - dipy

about:
  home: https://dipy.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Diffusion MR Imaging in Python

extra:
  recipe-maintainers:
    - arokem
    - garyfallidis
    - skoudoro
