{% set version = "1.8.0" %}
{% set name = "dipy" %}

package:
  name: dipy
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: cc3845585b6ccd5d7bf43094d52a00eb73111072eee36c2149fabdb1b071f008
build:
  number: 0
  script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64   # [win64 and vc==14]
    - python -m pip install --no-deps --ignore-installed .

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - meson-python
    - ninja
  host:
    - python
    - numpy
    - nibabel
    - cython
    - pip
    - tqdm
    - h5py
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - nibabel
    - scikit-learn
    - matplotlib-base
    - cvxpy   # [py<39]
    - pytables
    - vtk  # [py<39]
    - tqdm
    - h5py
    - pandas
    - scikit-image
    - statsmodels

test:
  imports:
    - dipy

about:
  home: https://dipy.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Diffusion MR Imaging in Python

extra:
  recipe-maintainers:
    - arokem
    - garyfallidis
    - skoudoro
