{% set version = "0.13.0" %}

package:
  name: dipy
  version: {{ version }}

source:
  fn: dipy-{{ version }}.tar.gz
  url:
    https://pypi.python.org/packages/26/52/a64d196965ec1455371347684a910d3f62aee1d3dac07d00cc68ea5230d0/dipy-{{ version }}.tar.gz
  md5: 3c3589974e4cc5b71d7e4e6d563dcbfa

build:
    number: 1
    script: python setup.py install
    features:
        - vc9  # [win and py27]
        - vc10  # [win and py34]
        - vc14  # [win and py35]

requirements:
  build:
    - python
    - numpy
    - nibabel
    - cython
    - gcc  # [not win]
  run:
    - python
    - numpy
    - scipy
    - nibabel
    - scikit-learn
    - matplotlib
    - cvxopt  # [not win]
    - pytables
    - libgcc  # [not win]
    - vtk  # [py27]
test:
  imports:
    - dipy

about:
  home: https://nipy.org/dipy
  license:  3-clause BSD
  license_file: LICENSE
  summary: Diffusion MR Imaging in Python

extra:
  recipe-maintainers:
    - arokem
    - garyfallidis
