{% set version = "1.10.0" %}
{% set name = "dipy" %}

package:
  name: dipy
  version: {{ version }}

source:
  url: https://pypi.org/packages/source/{{ name[0] }}/{{ name }}/{{ name }}-{{ version }}.tar.gz
  sha256: b9c8559c1ceec118bd8ebafa1c654582fc13d64c66266ca4d15a2df2367be870
build:
  number: 1
  skip: true  # [py<39]
  script:
    - call "C:\Program Files (x86)\Microsoft Visual Studio 14.0\VC\vcvarsall.bat" x86_amd64   # [win64 and vc==14]
    - mkdir builddir  # [arm64 and osx]
    - ${PYTHON} $(which meson) setup ${MESON_ARGS} builddir || (cat builddir/meson-logs/meson-log.txt && exit 1)  # [arm64 and osx]
    - ${PYTHON} -m build --wheel --no-isolation --skip-dependency-check -Cbuilddir=builddir  # [arm64 and osx]
    - ${PYTHON} -m pip install dist/dipy*.whl  # [arm64 and osx]
    - python -m pip install --no-deps --ignore-installed .  # [not arm64]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_{{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - {{ compiler('c') }}
    - {{ stdlib("c") }}
    - {{ compiler('cxx') }}
  host:
    - python
    - python-build
    - meson-python
    - numpy
    - ninja
    - pkg-config
    - cython
    - pip
    - packaging
  run:
    - python
    - {{ pin_compatible('numpy') }}
    - scipy
    - nibabel
    - trx-python
    - scikit-learn
    - matplotlib-base
    - cvxpy   # [py<39]
    - pytables
    - vtk  # [py<39]
    - tqdm
    - h5py
    - pandas
    - scikit-image
    - statsmodels

test:
  imports:
    - dipy

about:
  home: https://dipy.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Diffusion MR Imaging in Python

extra:
  recipe-maintainers:
    - arokem
    - garyfallidis
    - skoudoro
