context:
  name: "dipy"
  version: 1.11.0
  python_min: "3.10"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 5f9247ea7eee267305b02a7265bb0fe2d6918760b39c8fa6debfe8df7098ddd8
build:
  number: 0
  script:
    - mkdir builddir  # [arm64 and osx]
    - ${{ PYTHON }} $(which meson) setup ${MESON_ARGS} builddir || (cat builddir/meson-logs/meson-log.txt && exit 1)  # [arm64 and osx]
    - ${{ PYTHON }} -m build --wheel --no-isolation --skip-dependency-check -Cbuilddir=builddir  # [arm64 and osx]
    - ${{ PYTHON }} -m pip install dist/dipy*.whl  # [arm64 and osx]
    - ${{ PYTHON }} -m pip install . -vv  # [not (arm64 and osx)]

requirements:
  build:
    - python                                 # [build_platform != target_platform]
    - cross-python_${{ target_platform }}     # [build_platform != target_platform]
    - cython                                 # [build_platform != target_platform]
    - ninja                                  # [build_platform != target_platform]
    - pkg-config                             # [build_platform != target_platform]
    - meson-python                           # [build_platform != target_platform]
    - numpy                                  # [build_platform != target_platform]
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python >=${{ python_min }}
    - python-build
    - meson-python
    - numpy
    - ninja
    - pkg-config
    - cython
    - pip
    - packaging
  run:
    - python >=${{ python_min }}
    - numpy >=1.21.4
    - scipy
    - nibabel
    - trx-python
    - scikit-learn
    - matplotlib-base
    - pytables
    - tqdm
    - h5py
    - pandas
    - scikit-image
    - statsmodels

tests:
  - python:
      imports:
        - dipy

about:
  homepage: https://dipy.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Diffusion MR Imaging in Python
  repository: https://github.com/dipy/dipy
  documentation: https://dipy.org

extra:
  recipe-maintainers:
    - arokem
    - garyfallidis
    - skoudoro
