schema_version: 1

context:
  name: dipy
  version: "1.12.0"

package:
  name: ${{ name }}
  version: ${{ version }}

source:
  url: https://pypi.org/packages/source/${{ name[0] }}/${{ name }}/${{ name }}-${{ version }}.tar.gz
  sha256: 12523cd9dfe8a9c37f18a24c5a8cbad9cdb6bc8f52bf2671c51f891ed2bb7734
build:
  number: 1
  skip: match(python, "<3.11")
  script:
    - if: arm64 and osx
      then:
        - mkdir builddir
        - ${PYTHON} $(which meson) setup ${MESON_ARGS} builddir || (cat builddir/meson-logs/meson-log.txt && exit 1)
        - ${PYTHON} -m build --wheel --no-isolation --skip-dependency-check -Cbuilddir=builddir
        - ${PYTHON} -m pip install dist/dipy*.whl
      else: ${{ PYTHON }} -m pip install . -vv --no-deps --no-build-isolation
requirements:
  build:
    - if: build_platform != target_platform
      then:
        - python
        - cross-python_${{ target_platform }}
        - cython
        - ninja
        - pkg-config
        - meson-python
        - numpy
    - ${{ compiler('c') }}
    - ${{ stdlib('c') }}
    - ${{ compiler('cxx') }}
  host:
    - python
    - python-build
    - meson-python
    - numpy
    - scipy
    - ninja
    - pkg-config
    - cython
    - pip
    - packaging
  run:
    - python
    - numpy >=1.22.4
    - scipy >=1.8
    - nibabel >=3.0.0
    - trx-python >=0.4.0
    - tqdm >=4.30.0
    - h5py >=3.1.0
    - packaging >=21

tests:
  - python:
      imports:
        - dipy

about:
  homepage: https://dipy.org
  license: BSD-3-Clause
  license_file: LICENSE
  summary: Diffusion MR Imaging in Python
  repository: https://github.com/dipy/dipy
  documentation: https://dipy.org

extra:
  recipe-maintainers:
    - arokem
    - garyfallidis
    - skoudoro
