travis:
  secure:
    BINSTAR_TOKEN: kVYF/gRdDVrJbECyN67UIvFRgxszDSwIvdcDtgGkPUikv+DUE0i9aw79xQA2NMajMBen/RVxzq3lxC9q1pjaL4PetxeksBM5bnkX0Tupk/H71LfW2I9zLk0zCWdOgD7719WkwcUif+UGfbkQP7mFePedWjiPUGDODwWfhc5aeJLF7oQ1QtflT9s1yrycUySXvAVs0c5vQLaK/Y+1Mxv7IaTpYYfUG0w9IrbXygb/QjidQrpnolkrwBV6NKl2/hU2uKQyF7YiQnBWHlBBkrb3k36GNjYMoDiiuIeEqG//Gdy0jtLL7bbbZWIN+rdIqxztL7/OCLuRDF3ujMof0jzxYphS3fXYrelVLZ7XFDnHy8ogZB5sxXWwvrR19xV4gzJdBdvQzfxdEdrR3qK+SSmRXtN9yDFbGCBj+HWclshKVKJZFwXq+5QqGPk6f/bKFYat/T9RmJQD6EfXrdWmErpq4qLP12my13/BPo91r0UsYkEnGBD1iMF22nAN+asWzVfdA41FMy24fZXkHQgoG2JoXuZCH4ssqu3Saw81HH+5PEbV/cn7dKhokerN4lzhT71jcAd/mgVSYCAlFeRm1kQaYtS8c4VMhz2kY61xebgZiru0AIx2HyA41xNsyc3jLj5cbxXUhHMw9PL6Xp8caJ/UK/dpSIxBDUmMeZ72oh6DXdo=
appveyor:
  secure:
    BINSTAR_TOKEN: tumuXLL8PU75WMnRDemRy02ruEq2RpNxeK3dz0MjFssnosPm2v4EFjfNB4PTotA1
provider:
  win: azure
